Third homework
iiraskin/android_mobile_development_course pull request #4
Opened 2019-11-09 21:42 UTC by iiraskin

2019-11-11 12:13 UTC, IvanShafran requested changes
Поправь, пожалуйста, замечания

2019-11-11 12:13 UTC, IvanShafran commented on Homework3/src/Main.java
> +                System.out.println((char)i + " " + symbols[i]);
Выводить тоже надо в файл

2019-11-11 12:13 UTC, IvanShafran commented on Homework3/src/SymbolsCount.java
> +        // но, мне кажется, тут лучше и проще использовать обычный массив
Да, норм)

2019-11-11 12:13 UTC, IvanShafran commented on Homework3/src/SymbolsCount.java
> +        int[] counter = new int[65536];
Можно использовать Character.MAX_VALUE вместо константы, думаю

2019-11-11 12:13 UTC, IvanShafran commented on Homework3/src/SymbolsCount.java
> +        try {
Важно закрывть ресурсы всегда.
Наиболее простой вариант try with resources http://xn----htbdsuo3h.xn--p1ai/try-%D1%81-%D1%80%D0%B5%D1%81%D1%83%D1%80%D1%81%D0%B0%D0%BC%D0%B8-%D0%B2-java/

2019-11-11 12:13 UTC, IvanShafran commented on Homework3/src/SymbolsCount.java
> +            FileReader reader = new FileReader(new File(fileName));
Надо обернуть в BufferedReader, т.к. чтение по одному байту из файла очень неэффективно

2019-11-11 20:12 UTC, iiraskin commented on Homework3/src/SymbolsCount.java
> +            FileReader reader = new FileReader(new File(fileName));
Что небуферизованный ввод неэффективный, это понятно. Но я так понял требование "посимвольно" в условии

2019-11-11 20:13 UTC, iiraskin commented on Homework3/src/Main.java
> +                System.out.println((char)i + " " + symbols[i]);
Когда делал, такого условия ещё не было)

2019-11-13 10:39 UTC, IvanShafran commented on Homework3/src/SymbolsCount.java
> +            FileReader reader = new FileReader(new File(fileName));
Ага, но BufferedReader позволяет читать посимвольно и при этом эффективно, т.к. внутри себя сам буфферизирует

2019-11-13 10:40 UTC, IvanShafran approved these changes
Отличная работа!

2019-11-13 10:40 UTC, merged